### ISSUE TITLE
Didn't find exploded-aar directory

### ISSUE THREAD

**Issue by jboxx** [WanghongLin/OpenCV4Android#1]
Hi thanks for this useful OpenCV wrapper, I was trying to fetch the library from jcenter and was build it. but the exploded-aar not generated. any suggestion?

I use
Android Studio: 3.5.1
gradle build 3.5.1

**Comment by WanghongLin** [comment]
Thanks for your feedback, it looks like the exploded aar has been removed and the equivalent is  `~/.gradle/caches/transforms-2/file-2.1` for the newest Android studio.

The temporary workaround or solution is find include directory under gradle transform directory, and add it to cmake include path.

In my environment it is

`~/.gradle/caches/transforms-2/files-2.1/65e17d0b4026aa7ecefacd8e395a2acd/opencv-with-header-3.1.0-dev/cpp/include`

**Comment by jboxx** [comment]
I think it's too hard when we want to implement this with a project that has a lot of people to collaborate.

Maybe can use this library https://github.com/howardpang/androidNativeBundle to embed the header

**Comment by WanghongLin** [comment]
I have used `androidNativeBundle` to publish the aar and verify it works good. See if it works on your side or not. Anyway, `androidNativeBundle` is an amazing tools.
